'use strict';

/**
 * Finds the unit/building icons for a step's action text.
 *
 * Steps are free-form Korean ("해병 계속 생산", "보급고 → 병영"), so the terms are
 * matched as substrings, longest first: 병영 기술실 wins over a bare 병영, and
 * 궤도 사령부 over 사령부. Anything unrecognised simply gets no icon and the
 * text stands on its own.
 *
 * `assets/icons/manifest.json` is generated by `tools/fetch-icons.js`.
 */

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

let terms = [];
let baseUrl = null;
let loadError = null;

/**
 * @param dir directory holding the PNGs and `manifest.json`
 * @returns { count, error } — `error` is reported rather than thrown so a
 *   missing icon set degrades to the text-only overlay instead of no overlay.
 */
function load(dir) {
  terms = [];
  baseUrl = null;
  loadError = null;
  try {
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'));
    const entries = Object.entries(manifest.terms || {});
    // Longest first so a composed name is preferred over the building inside it.
    entries.sort((a, b) => b[0].length - a[0].length);
    terms = entries.map(([term, file]) => ({ term, file: file + '.png' }));
    baseUrl = pathToFileURL(dir + path.sep).href;
  } catch (err) {
    loadError = err.message;
  }
  return { count: terms.length, error: loadError };
}

const loaded = () => terms.length > 0;

/**
 * Icons for one action line, in the order the terms appear in the text.
 * @returns [{ term, src }]
 */
function iconsFor(action, max = 3) {
  const text = String(action || '');
  if (!text || !loaded()) return [];

  const taken = new Array(text.length).fill(false);
  const found = [];

  for (const { term, file } of terms) {
    let from = 0;
    for (;;) {
      const at = text.indexOf(term, from);
      if (at < 0) break;
      from = at + 1;
      let free = true;
      for (let i = at; i < at + term.length; i += 1) if (taken[i]) { free = false; break; }
      if (!free) continue;
      for (let i = at; i < at + term.length; i += 1) taken[i] = true;
      found.push({ at, term, src: baseUrl + file });
    }
  }

  found.sort((a, b) => a.at - b.at);

  // The same picture twice says nothing: `사령부 궤도 사령부로 변환` matches 사령부
  // at both ends, and 궤도 사령부 has no icon of its own to distinguish them.
  const seen = new Set();
  const unique = found.filter(({ src }) => !seen.has(src) && seen.add(src));

  return unique.slice(0, max).map(({ term, src }) => ({ term, src }));
}

module.exports = { load, loaded, iconsFor };
