'use strict';

/**
 * Finds the unit/building icons for a step's action text.
 *
 * Steps are free-form Korean ("해병 계속 생산", "보급고 → 병영"), so the terms are
 * matched as substrings, longest first: 병영 기술실 wins over a bare 병영, and
 * 궤도 사령부 over 사령부. Anything unrecognised simply gets no icon and the
 * text stands on its own.
 *
 * `assets/icons/manifest.json` is generated by `tools/fetch-icons.js`.
 */

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

let terms = [];
let baseUrl = null;
let loadError = null;
let haveImages = false;

/**
 * @param dir directory holding the PNGs and `manifest.json`
 * @returns { count, error } — `error` is reported rather than thrown so a
 *   missing icon set degrades to the text-only overlay instead of no overlay.
 */
function load(dir) {
  terms = [];
  baseUrl = null;
  loadError = null;
  haveImages = false;
  try {
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'));
    const entries = Object.entries(manifest.terms || {});
    // Longest first so a composed name is preferred over the building inside it.
    entries.sort((a, b) => b[0].length - a[0].length);
    terms = entries.map(([term, file]) => ({ term, file: file + '.png' }));
    baseUrl = pathToFileURL(dir + path.sep).href;
    /* The manifest ships with the app; the images do not — they are fetched on
       request. So a readable manifest says nothing about whether there is
       anything to draw, and on a fresh install there is not. Sampling one file
       is enough to tell the two states apart, and cheap enough to do on every
       load. */
    haveImages = terms.some((t) => fs.existsSync(path.join(dir, t.file)));
  } catch (err) {
    loadError = err.message;
  }
  return { count: terms.length, error: loadError };
}

/* True only when there are pictures to draw. The control window shows the
   내려받기 button on the strength of this, so answering yes for a manifest with
   no images behind it left a new install with empty icon slots and nothing on
   screen explaining how to fill them. */
const loaded = () => terms.length > 0 && haveImages;

/**
 * Icons for one action line, in the order the terms appear in the text.
 * @returns [{ term, src }]
 */
function iconsFor(action, max = 3) {
  const text = String(action || '');
  if (!text || !loaded()) return [];

  const taken = new Array(text.length).fill(false);
  const found = [];

  for (const { term, file } of terms) {
    let from = 0;
    for (;;) {
      const at = text.indexOf(term, from);
      if (at < 0) break;
      from = at + 1;
      let free = true;
      for (let i = at; i < at + term.length; i += 1) if (taken[i]) { free = false; break; }
      if (!free) continue;
      for (let i = at; i < at + term.length; i += 1) taken[i] = true;
      found.push({ at, term, src: baseUrl + file });
    }
  }

  found.sort((a, b) => a.at - b.at);

  // The same picture twice says nothing: `사령부 궤도 사령부로 변환` matches 사령부
  // at both ends, and 궤도 사령부 has no icon of its own to distinguish them.
  const seen = new Set();
  const unique = found.filter(({ src }) => !seen.has(src) && seen.add(src));

  return unique.slice(0, max).map(({ term, src }) => ({ term, src }));
}

/**
 * Every term the manifest knows, for the editor's suggestions.
 *
 * Shortest first — the opposite of the matching order. Matching wants the
 * longest name that fits so `병영 기술실` beats `병영`; a person typing 병 wants
 * to see `병영` before `병영 기술실`.
 *
 * `src` is null when the images have not been downloaded, so the caller can
 * offer the names without pretending there are pictures behind them.
 */
function allTerms() {
  const withImages = loaded();
  return [...terms]
    .sort((a, b) => a.term.length - b.term.length || a.term.localeCompare(b.term))
    .map(({ term, file }) => ({ term, src: withImages ? baseUrl + file : null }));
}

module.exports = { load, loaded, iconsFor, allTerms };
